//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satisprogram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisID { get; set; }
        public int KullaniciID { get; set; }
        public int UrunID { get; set; }
        public int SatisAdedi { get; set; }
        public double ToplamTutar { get; set; }
        public System.DateTime SatisZamani { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
